export { syncPlugin } from './plugin'
export { syncOpsDriverPlugin } from './drivers/ops-sync-driver-plugin'
export { sseSubscribeDriverPlugin } from './drivers/sse-subscribe-driver-plugin'
export { SYNC_DRIVER_CAPABILITY_KEY, SYNC_SUBSCRIBE_CAPABILITY_KEY, getSyncDriver, getSyncSubscribeDriver, registerSyncDriver, registerSyncSubscribeDriver } from './capabilities'
export type { SyncOpsDriverPluginOptions } from './drivers/ops-sync-driver-plugin'
export type { SseSubscribeDriverPluginOptions } from './drivers/sse-subscribe-driver-plugin'
export type { SyncPluginOptions, SyncExtension } from './types'
