export { executeLocalQuery, evaluateWithIndexes } from './engine/local'
export { normalizeQuery, normalizeSort } from './normalize'
export { encodeCursorToken, decodeCursorToken } from './cursor'
export { buildQueryMatcherOptions } from './matcherOptions'
export { summarizeQuery } from './summary'
export { resolveCachePolicy, type CacheWriteDecision } from './cachePolicy'
